//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBA_HOTEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleaningRoomDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CleaningRoomDetail()
        {
            this.CleaningRoomItems = new HashSet<CleaningRoomItem>();
        }
    
        public int ID { get; set; }
        public int CleaningRoomID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime FinishDateTime { get; set; }
        public string Note { get; set; }
        public string StatusCleaning { get; set; }
    
        public virtual Cleaning_Room Cleaning_Room { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CleaningRoomItem> CleaningRoomItems { get; set; }
    }
}
